In [133]:
import numpy as np

print(-(2**16) / 2)
print((2 ** 16) / 2)

-32768.0
32768.0


In [134]:
a = np.int8(25)
print(a)
print(type(a))

25
<class 'numpy.int8'>


In [135]:
print(np.iinfo(np.int8))
print(np.iinfo(np.int16))
print(np.iinfo(np.int32))
print(np.iinfo(np.int64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [136]:
b = np.uint8(124)
print(b)
print(type(b))
np.iinfo(b)

124
<class 'numpy.uint8'>


iinfo(min=0, max=255, dtype=uint8)

In [137]:
print(np.finfo(np.float16))

print(np.finfo(np.float32))

Machine parameters for float16
---------------------------------------------------------------
precision =   3   resolution = 1.00040e-03
machep =    -10   eps =        9.76562e-04
negep =     -11   epsneg =     4.88281e-04
minexp =    -14   tiny =       6.10352e-05
maxexp =     16   max =        6.55040e+04
nexp =        5   min =        -max
smallest_normal = 6.10352e-05   smallest_subnormal = 5.96046e-08
---------------------------------------------------------------

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
smallest_normal = 1.1754944e-38   smallest_subnormal = 1.4012985e-45
---------------------------------------------------------------



In [138]:
print(np.sctypeDict)
print(len(np.sctypeDict))

{'bool': <class 'numpy.bool'>, 'float16': <class 'numpy.float16'>, 'float32': <class 'numpy.float32'>, 'float64': <class 'numpy.float64'>, 'longdouble': <class 'numpy.longdouble'>, 'complex64': <class 'numpy.complex64'>, 'complex128': <class 'numpy.complex128'>, 'clongdouble': <class 'numpy.clongdouble'>, 'bytes_': <class 'numpy.bytes_'>, 'str_': <class 'numpy.str_'>, 'void': <class 'numpy.void'>, 'object_': <class 'numpy.object_'>, 'datetime64': <class 'numpy.datetime64'>, 'timedelta64': <class 'numpy.timedelta64'>, 'int8': <class 'numpy.int8'>, 'byte': <class 'numpy.int8'>, 'uint8': <class 'numpy.uint8'>, 'ubyte': <class 'numpy.uint8'>, 'int16': <class 'numpy.int16'>, 'short': <class 'numpy.int16'>, 'uint16': <class 'numpy.uint16'>, 'ushort': <class 'numpy.uint16'>, 'int32': <class 'numpy.int32'>, 'intc': <class 'numpy.int32'>, 'uint32': <class 'numpy.uint32'>, 'uintc': <class 'numpy.uint32'>, 'int64': <class 'numpy.int64'>, 'long': <class 'numpy.int64'>, 'uint64': <class 'numpy.uint

In [139]:
a = np.uint8(456)
print(a)

OverflowError: Python integer 456 out of bounds for uint8

* Массивы NumPy

In [ ]:
import numpy as np

arr = np.array([1, 5, 2, 9, 10])
print(arr, type(arr))

[ 1  5  2  9 10] <class 'numpy.ndarray'>


In [ ]:
nd_arr = np.array([
    [12, 45, 78],
    [34, 56, 13],
    [12, 98, 76]
])

nd_arr.dtype

dtype('int64')

In [ ]:
arr = np.array([1, 2, 3, 4, 5], dtype=np.int8)
arr.dtype
arr[2] = 125.5
arr


array([  1,   2, 125,   4,   5], dtype=int8)

In [ ]:
arr = np.float128(arr)
arr

array([  1.,   2., 125.,   4.,   5.], dtype=float128)

In [ ]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr

array([12321, -1234,  3435,  -214,   100], dtype=int32)

In [ ]:
arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

In [ ]:
arr.ndim

1

In [ ]:
nd_arr.ndim

2

In [ ]:
arr.size

5

In [ ]:
nd_arr.size

9

In [ ]:
nd_arr.shape

(3, 3)

In [ ]:
arr.shape

(5,)

In [ ]:
arr.itemsize

1

In [ ]:
nd_arr.itemsize

8

In [ ]:
zeros_id = np.zeros(5)
zeros_id

array([0., 0., 0., 0., 0.])

In [ ]:
zeros_3d = np.zeros((5,4,3), dtype = np.float32)
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [ ]:
np.arange(5)
np.arange(2.5, 5)
np.arange(2.5, 5, 0.5, dtype=np.float16)


array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

In [ ]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

In [ ]:
arr = np.linspace(1, 2, 10, endpoint=False, retstep=True)
arr

(array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]), np.float64(0.1))

In [ ]:
arr = np.linspace(-6, 21, 60, endpoint=True, retstep=True)
arr

# от какого числа, до какого и сколько элементов 

(array([-6.        , -5.54237288, -5.08474576, -4.62711864, -4.16949153,
        -3.71186441, -3.25423729, -2.79661017, -2.33898305, -1.88135593,
        -1.42372881, -0.96610169, -0.50847458, -0.05084746,  0.40677966,
         0.86440678,  1.3220339 ,  1.77966102,  2.23728814,  2.69491525,
         3.15254237,  3.61016949,  4.06779661,  4.52542373,  4.98305085,
         5.44067797,  5.89830508,  6.3559322 ,  6.81355932,  7.27118644,
         7.72881356,  8.18644068,  8.6440678 ,  9.10169492,  9.55932203,
        10.01694915, 10.47457627, 10.93220339, 11.38983051, 11.84745763,
        12.30508475, 12.76271186, 13.22033898, 13.6779661 , 14.13559322,
        14.59322034, 15.05084746, 15.50847458, 15.96610169, 16.42372881,
        16.88135593, 17.33898305, 17.79661017, 18.25423729, 18.71186441,
        19.16949153, 19.62711864, 20.08474576, 20.54237288, 21.        ]),
 np.float64(0.4576271186440678))

In [ ]:
arr = np.linspace(-6,21,60, endpoint=False, retstep = True)
arr

(array([-6.  , -5.55, -5.1 , -4.65, -4.2 , -3.75, -3.3 , -2.85, -2.4 ,
        -1.95, -1.5 , -1.05, -0.6 , -0.15,  0.3 ,  0.75,  1.2 ,  1.65,
         2.1 ,  2.55,  3.  ,  3.45,  3.9 ,  4.35,  4.8 ,  5.25,  5.7 ,
         6.15,  6.6 ,  7.05,  7.5 ,  7.95,  8.4 ,  8.85,  9.3 ,  9.75,
        10.2 , 10.65, 11.1 , 11.55, 12.  , 12.45, 12.9 , 13.35, 13.8 ,
        14.25, 14.7 , 15.15, 15.6 , 16.05, 16.5 , 16.95, 17.4 , 17.85,
        18.3 , 18.75, 19.2 , 19.65, 20.1 , 20.55]),
 np.float64(0.45))

In [ ]:
import numpy as np
arr = np.arange(8)
arr

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
arr.shape = (2, 4)
arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape(2,4)
arr_new

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape((2,4), order = 'F')
arr_new

array([[0, 2, 4, 6],
       [1, 3, 5, 7]])

In [ ]:
arr = np.arange(8)
arr_new = arr.reshape(2,4)
arr_trans = arr_new.transpose()
arr_trans

array([[0, 4],
       [1, 5],
       [2, 6],
       [3, 7]])

In [2]:
import numpy as np
arr = np.arange(3)
print(arr)
print(arr.shape)
arr.transpose()
print(arr)


[0 1 2]
(3,)
[0 1 2]


In [ ]:
arr = np.linspace(1, 2, 6)
arr[2]

np.float64(1.4)

In [ ]:
print(arr[2:4])

[1.4 1.6]


In [ ]:
print(arr[::-1])

[2.  1.8 1.6 1.4 1.2 1. ]


In [ ]:
nd_array = np.linspace(0, 6, 12, endpoint=False).reshape(3,4)
nd_array

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [ ]:
nd_array[1][2]

np.float64(3.0)

In [ ]:
nd_array[1, 2]

np.float64(3.0)

In [ ]:
nd_array[:2, 2]

array([1., 3.])

In [ ]:
nd_array[1:,2:4]

array([[3. , 3.5],
       [5. , 5.5]])

In [ ]:
nd_array[:,2:4]

array([[1. , 1.5],
       [3. , 3.5],
       [5. , 5.5]])

In [ ]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots

/var/folders/90/5gtcpdnx1498r79_6_0yb7r00000gn/T/ipykernel_33318/3612371969.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [ ]:
sum(roots)

np.float64(nan)

In [ ]:
roots[np.isnan(roots)] = 0
roots

array([2.        , 3.        , 0.        , 1.73205081])

* Векторы NumPy

In [ ]:
import numpy as np

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

vec1 + vec2

array([14. , 10. , 10.6, 15.5])

In [ ]:
vec1 * vec2

array([24. , 24. , 25.2, 32.5])

In [ ]:
vec = np.arange(5)
vec * 10

array([ 0, 10, 20, 30, 40])

In [ ]:
vec1 > vec2

array([False, False,  True, False])

* длинна вектора

In [8]:

vec = np.array([2, 4, 7, 2.5])

lenght = np.sqrt(np.sum(vec ** 2))
print(lenght)

lenght = np.linalg.norm(vec)
print(lenght)

8.674675786448736
8.674675786448736


* расстояние между векторами

In [ ]:

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

distance = np.sqrt(np.sum((vec1 - vec2) ** 2))
distance

distance = np.linalg.norm(vec1 - vec2)
distance

np.float64(15.026975743641833)

* скалярное произвеление векторов

In [ ]:

vec1 = np.array([2, 4, 7, 2.5])
vec2 = np.array([12, 6, 3.6, 13])

scalar_product = np.sum(vec1 * vec2)
scalar_product

scalar_product = np.dot(vec1, vec2)
scalar_product

np.float64(105.7)

In [ ]:
x = np.array([25, 0])
y = np.array([0, 10])

scalar_prod = np.dot(x, y)
scalar_prod

np.int64(0)

In [ ]:
vec = np.array([2, 7, 18, 28, 1, 9, 8, 4])
print(vec.min())
print(vec.max())
print(vec.mean())

1
28
9.625


* Случайные числа

In [ ]:
import numpy as np
np.random.rand() * 100

30.927918476718276

In [ ]:
np.random.rand(5)

array([0.88189948, 0.33186615, 0.733915  , 0.77840524, 0.51490218])

In [ ]:
np.random.rand(2, 3)

array([[0.94188719, 0.00840663, 0.89196358],
       [0.28297358, 0.7824131 , 0.07124407]])

In [ ]:
shape = (3, 4)
np.random.rand(*shape)

array([[0.16309594, 0.00373377, 0.25209738, 0.61250841],
       [0.94804497, 0.04258665, 0.27042522, 0.08083493],
       [0.07386324, 0.95338671, 0.69005552, 0.72368756]])

In [ ]:
shape = (2, 3)
np.random.sample(shape)

array([[0.58713104, 0.3558234 , 0.97949032],
       [0.74204834, 0.56948815, 0.26309668]])

In [ ]:
np.random.uniform(low = 0.0, high = 1.0, size = None)

0.9680640956408757

In [ ]:
np.random.uniform(-1000, 500, size=(2,3))

array([[-538.31772713, -318.65523583, -334.4600397 ],
       [-974.24127721,  -85.00976466,  -98.51132492]])

In [3]:
np.random.randint(low=5, high = None, size=None, dtype =int)

3

In [ ]:
arr = np.arange(6)
print(arr)

print(np.random.shuffle(arr))
arr

[0 1 2 3 4 5]
None


array([3, 2, 5, 1, 4, 0])

In [ ]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]
shuffled = np.random.permutation(playlist)
print(shuffled)
print(playlist)

['The Beatles' 'ACDC' 'Pink Floyd' 'Deep Purple']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [ ]:
np.random.permutation(10)

array([5, 2, 6, 0, 4, 8, 7, 1, 3, 9])

In [ ]:
workers = ['Ivan', 'Nikita', 'Maria', 'John', 'Kate']

choise = np.random.choice(workers, size = 2, replace = False)
print(choise)

['Ivan' 'Maria']


In [ ]:
choice = np.random.choice([1,2,3,4,5,6], size=10, replace= True)
print(choice)

[6 4 6 3 6 2 4 6 6 6]


In [143]:
x = np.random.choice((np.arange(1, 21)), size = 10, replace = False)
x

array([19, 14, 16, 10,  7,  4, 12, 15,  6, 13])

In [144]:
np.random.seed(23)
np.random.randint(10, size = (3, 4))

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [4]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]


In [ ]:
# Не забудьте импортировать numpy и сразу задать seed 2021
import numpy as np
np.random.seed(2021)
# В simple сохраните случайное число в диапазоне от 0 до 1
simple = np.random.rand()

# Сгенерируйте 120 чисел в диапазоне от -150 до 2021, сохраните их
# в переменную randoms
randoms = np.random.uniform(-150, 2021, size=120)

# Получите массив из случайных целых чисел от 1 до 100 включительно
# из 3 строк и 2 столбцов. Сохраните результат в переменную table
table = np.random.randint(1, 101, size=(3,2))

# В переменную even сохраните чётные числа от 2 до 16 включительно
even = np.arange(2,17,2)

# Скопируйте even в переменную mix. Перемешайте числа в mix так, чтобы массив mix изменился
mix = even.copy()
np.random.shuffle(mix)

# Получите из even 3 числа без повторений. Сохраните их в переменную select
select = np.random.choice(even, replace=False, size=3)

# Получите переменную triplet, которая должна содержать перемешанные
# значения из массива select (сам select измениться не должен)
triplet = np.random.permutation(select)

In [11]:
import numpy as np
simplelist = [19, 242, 14, 152, 142, 1000]

np.mean(simplelist)

np.float64(261.5)